export default {
    nav: {
        intro: 'Intro',
        mission: 'Mission',
        music: 'Music'
    },
    intro: {
        introCopy: [
            "We’re an independent band committed to making music outside the mainstream. We don’t release our songs on streaming platforms, and we refuse to take part in the traditional circuits of the music business. No labels, no algorithms, no compromises — just music made with heart, intention, and total creative freedom.",
            "Every song we share is a piece of who we are. We record, produce, and distribute everything ourselves because we believe music should come straight from the artist to the listener — raw, real, and unfiltered. We're not in it for the charts or the fame. We’re in it because we love what we do, and we want to share that with those who genuinely care.",
            "When you support us, you’re not just buying a track — you’re keeping this dream alive, helping us fund new gear, write new songs, and stay completely independent. Thank you for being part of something real."
        ],
    },
    mission: {
        title: 'Our Mission',
        articleOneH1: 'The Echoes of Exploitation: A Century of Musical Chains',
        missionCopy: [
            "Underground music is a mindset: a fierce independence from commercial trends and industry expectations. It's raw, authentic, and born from creative urgency, not market formulas.",
            "The past two decades transformed music, from piracy's disruption to social media's promise of direct artist-fan connection. Yet, this freedom came with a catch. Algorithms on streaming platforms became new gatekeepers, devaluing music and forcing independent artists into a relentless cycle of content creation—chasing likes and trends just to be seen. Music became background noise, its depth sacrificed for fleeting visibility.",
            "That's why we don't stream or chase algorithmic approval. We believe our music deserves more than passive consumption. We refuse a system that undervalues artists and prioritizes viral trends over genuine artistry. We seek a direct connection: no middlemen, no gatekeepers—just us and you, the listener.",
            "This is our underground rock & roll: loud, honest, and entirely ours. We make music because we mean it, not to follow trends or please algorithms. We stand for music as art, rebellion, and truth. If you're here, you do too. Thank you for keeping real music alive.",
            "If you want to dive deeper into our reasoning, here's a couple of longer articles"
        ],
        article_one: [
            "For over a century, the mainstream music industry has spun a captivating narrative of artistic dreams coming true. Yet, behind the glittering facade of fame and fortune, a different story unfolded – one of systemic exploitation, predatory contracts, and the relentless prioritization of profit over genuine artistry. Our band stands firmly against this entrenched model, and to understand why, we must first look back at the historical chains that have bound musicians for generations (other than the obvious fact that no major label -nor any minor nor minuscule one- offered us a fair contract).",
            "The dawn of recorded music brought with it the promise of wider reach, but also the first inkling of trouble for artists. In the bustling creative crucible of Tin Pan Alley in the early 20th century, songwriters and composers were often paid a flat fee for their creations, relinquishing all future rights and royalties. Imagine pouring your soul into a song, only for it to be owned and profited from by someone else, forever. This set a dangerous precedent: the value of the art was separated from the labor and intellectual property of the artist.",
            "As record labels emerged, the power imbalance solidified. Early record deals were notorious for their labyrinthine clauses, often indecipherable to the very artists signing them. Advances, presented as a lifeline for struggling musicians, were in reality recoupable debts. This meant that every penny spent by the label on recording, marketing, and touring had to be paid back by the artist from their meager share of future royalties. Many artists found themselves perpetually in debt to their labels, even as their music sold millions. The dream of a comfortable living often remained just that – a dream.",
            "The mid-20th century saw the rise of the iconic rock and roll era, yet the exploitation continued unabated. Artists signed away their publishing rights, the most valuable asset in the music business, often for a pittance. Publishing income, generated from the use of songs in films, commercials, and cover versions, became a cash cow for labels and publishers, while the creators saw only a fraction of its true worth. Bands were often locked into multi-album deals, regardless of their success, forcing them to churn out music on a relentless schedule dictated by corporate timelines, not creative inspiration. Creative control was a foreign concept; the label often had final say on everything from song selection to album artwork, molding artists into marketable products rather than nurturing their unique visions.",
            "The arrival of MTV in the 1980s ushered in a new era of visual spectacle, but also a new layer of control. While music videos became essential for promotion, their exorbitant costs were frequently borne by the artists, further deepening their debt to the labels. The emphasis shifted from raw musical talent to polished image and manufactured charisma. Bands were packaged and presented, their individuality often smoothed over to fit a mainstream aesthetic. The industry's hunger for hits led to a homogenization of sound, with A&R executives pushing artists towards commercially viable formulas rather than artistic experimentation. Bands that dared to defy these norms often found themselves sidelined or dropped.",
            "Throughout these decades, countless stories emerged of artists being financially crippled, creatively stifled, and ultimately discarded by the very industry that supposedly championed them. From TLC famously filing for bankruptcy despite selling millions of records due to predatory contracts, to Little Richard’s lifelong struggle to reclaim his publishing rights, the narrative is painfully consistent. The music industry, at its core, was built on an extractive model, where the creative output of artists was treated as a commodity to be bought low and sold high, with little regard for the human beings behind the melodies.",
            "This deeply ingrained history of exploitation is not just a cautionary tale; it's the very foundation upon which our band’s ethos is built. We refuse to participate in a system that has consistently devalued artists and commodified art. We believe in a different path, one rooted in authenticity, independence, and a direct connection between creators and those who truly appreciate their work. This historical context isn't just a lament; it's a declaration of our commitment to forging a new way forward, free from the echoes of exploitation that have plagued music for far too long."
        ],
        article_two: [
            "The turn of the millennium promised a revolution. The internet, initially heralded as the ultimate democratizer, was supposed to liberate artists from the clutches of the traditional industry. The era of piracy, while disruptive, inadvertently highlighted the power of direct access. Then came social media, offering artists direct lines to their fans. But what began as a promise of freedom has, for many, morphed into a new, insidious form of control: the algorithmic chains of the streaming era. Our band understands these digital dilemmas intimately, and it's precisely why we've chosen a radically different path, prioritizing music above all else.",
            "Initially, the digital landscape felt like a boundless frontier. Musicians could connect with listeners globally, share their work with unprecedented ease, and bypass the traditional gatekeepers. Yet, as the years progressed, new gatekeepers emerged, cloaked in the seemingly neutral guise of streaming platforms and their algorithms. These platforms, while offering convenience to listeners, have systematically devalued music and, by extension, the artists who create it. The payment models are notoriously opaque and minuscule, making it virtually impossible for most artists to earn a living wage from streams alone.",
            "For new and emerging bands, the situation is even more dire. The algorithm has become the new A&R, dictating what gets heard and by whom. Artists are forced onto a relentless \"content\" treadmill, pressured to produce constant short-form videos, participate in fleeting trends, and chase viral moments to gain even a sliver of visibility. The focus shifts from crafting timeless music to generating disposable content, fragmenting creative energy and sacrificing artistic depth for fleeting algorithmic favor. This isn't about fostering art; it's about feeding an insatiable digital beast.",
            "What's worse, the algorithmic age has contributed to the rise of \"processed\" music. Think about the sterile, committee-driven tracks churned out by major labels – often the result of multiple, anonymous songwriters and producers meticulously crafting a sound designed to fit market formulas and appeal to the widest possible audience. Talent shows further exemplify this trend, reducing genuine artistic expression to a competitive spectacle, where marketability often trumps raw talent and unique vision. Authenticity is sacrificed at the altar of mass appeal, and the soul of the music is lost in the pursuit of a manufactured hit.",
            "This is where our band draws a firm line in the digital sand. We reject the algorithmic chains and the content treadmill. We refuse to compromise our artistic integrity for fleeting trends or the whims of a corporate algorithm. For us, the music is paramount. It is the beginning, the middle, and the end of our creative process. Every note, every lyric, every rhythm is crafted with unwavering dedication to our artistic vision, not to a market formula.",
            "Our solution is born from this unwavering commitment to artistic purity: we are 100% self-sufficient and fiercely independent. There are no labels, no corporate overlords, no algorithms dictating our sound. We self-fund every aspect of our creative output.",
            "When you listen to our music, you are experiencing something genuinely authentic. You're supporting artists who pour their entire being into their craft, unburdened by corporate agendas or algorithmic pressures. You're part of a movement that believes in the intrinsic value of music, not just its potential for passive consumption. We are not a product; we are a passion. We are not content; we are artists. We are breaking the algorithmic chains, one authentic note at a time, and inviting you to join us on this rebellious journey."
        ]
    },
    music: {
        title: 'Listen & Support',
    }
}