export default {
  intro: [
    "We’re an independent band committed to making music outside the mainstream. We don’t release our songs on streaming platforms, and we refuse to take part in the traditional circuits of the music business. No labels, no algorithms, no compromises — just music made with heart, intention, and total creative freedom.",
    "Every song we share is a piece of who we are. We record, produce, and distribute everything ourselves because we believe music should come straight from the artist to the listener — raw, real, and unfiltered. We're not in it for the charts or the fame. We’re in it because we love what we do, and we want to share that with those who genuinely care.",
    "When you support us, you’re not just buying a track — you’re keeping this dream alive, helping us fund new gear, write new songs, and stay completely independent. Thank you for being part of something real."
  ],
  mission: [
    "Underground music isn’t just a genre — it’s a mindset. It represents a choice to exist outside of what’s expected, what’s safe, and what’s profitable. It’s music that isn’t shaped by commercial formulas or polished for the charts, but carved from raw emotion, lived experience, and creative urgency. Being underground means not waiting for permission. It means creating because you have to, not because the industry says it’s time. It’s a form of resistance and a declaration of independence — from trends, from markets, and from the machinery of mass consumption.",
    "In the past 20 years, the music industry has transformed beyond recognition. It started with the collapse of traditional sales due to piracy — peer-to-peer platforms like Napster and LimeWire gave everyone instant access to music for free. Then came the social media revolution: MySpace, YouTube, Facebook — each platform promised freedom for artists to share their work directly with listeners. But that freedom came with a cost. As algorithms evolved, they began to dictate what people heard, favoring volume and virality over substance. Streaming platforms became the new gatekeepers, dressed in the clothes of accessibility, but paying artists less than ever before.",
    "We’ve watched as the pressure on independent musicians has only increased. Not only do we have to write and record the music ourselves, but we’re also expected to promote it endlessly — posting reels, clips, behind-the-scenes footage, trending sounds — just to stay visible for a few seconds in a feed that resets every day. The art becomes background noise, swallowed up by a digital world where value is measured in likes and watch time, not depth or meaning. Somewhere along the way, music stopped being the destination and became just another form of content.",
    "That’s why we don’t stream. That’s why we don’t waste our lives chasing algorithm gods or trying to compete with lifestyle influencers and cat videos. We believe our music deserves better. We believe the people who connect with our songs want something more than passive background noise. We don’t want to be part of a system that gives everything away for nothing and expects artists to feel grateful for it. We want a direct connection. No middlemen. No gatekeepers. Just us and you, the listener.",
    "This is underground rock & roll. It’s loud, it’s honest, it’s imperfect — and it’s completely ours. We make it because we mean it. We don’t follow trends. We don’t dilute ourselves to please playlists. We stand for music as art, as rebellion, as truth. And if you’re here, it means you do too. So thank you — for showing up, for listening, for keeping something real alive."
  ]
}