export default {
    nav: {
        intro: 'Introducción',
        mission: 'Misión',
        music: 'Música'
    },
    intro: {
        introCopy: [
            "Somos una banda independiente comprometida a hacer música fuera del circuito comercial. No publicamos nuestras canciones en plataformas de streaming y nos negamos a formar parte de los mecanismos tradicionales de la industria musical. Sin sellos, sin algoritmos, sin compromisos — solo música hecha con corazón, intención y total libertad creativa.",
            "Cada canción que compartimos es una parte de quienes somos. Grabamos, producimos y distribuimos todo por nuestra cuenta porque creemos que la música debe ir directamente del artista al oyente — cruda, real y sin filtros. No lo hacemos por los rankings ni por la fama. Lo hacemos porque amamos lo que hacemos y queremos compartirlo con quienes realmente lo valoran.",
            "Cuando nos apoyas, no solo compras una canción — estás manteniendo este sueño vivo, ayudándonos a financiar nuevo equipo, escribir nuevas canciones y seguir siendo totalmente independientes. Gracias por ser parte de algo real."
        ]
    },
    mission: {
        title: 'Nuestra Misión',
        articleOneH1: 'Los Ecos de la Explotación: Un Siglo de Cadenas Musicales',
        missionCopy: [
            "La música underground es una actitud: una independencia feroz de las tendencias comerciales y las expectativas de la industria. Es cruda, auténtica y nace de una urgencia creativa, no de fórmulas de mercado.",
            "Las últimas dos décadas transformaron la música: desde la disrupción de la piratería hasta la promesa de conexión directa entre artistas y fans por redes sociales. Pero esa libertad vino con trampa. Los algoritmos de las plataformas de streaming se convirtieron en los nuevos guardianes, devaluando la música y obligando a los artistas independientes a un ciclo interminable de creación de contenido — persiguiendo likes y tendencias solo para ser vistos. La música se convirtió en ruido de fondo, su profundidad sacrificada por una visibilidad pasajera.",
            "Por eso no hacemos streaming ni buscamos la aprobación de algoritmos. Creemos que nuestra música merece más que consumo pasivo. Rechazamos un sistema que devalúa a los artistas y prioriza lo viral sobre lo auténtico. Queremos una conexión directa: sin intermediarios, sin guardianes — solo nosotros y tú, el oyente.",
            "Este es nuestro rock & roll underground: fuerte, honesto y completamente nuestro. Hacemos música porque lo sentimos, no para seguir modas ni complacer algoritmos. Defendemos la música como arte, rebeldía y verdad. Si estás aquí, tú también lo haces. Gracias por mantener viva la música real.",
            "Si quieres profundizar en nuestras razones, aquí tienes dos artículos más largos"
        ],
        article_one: [
            "Durante más de un siglo, la industria musical dominante ha tejido una narrativa seductora sobre sueños artísticos hechos realidad. Sin embargo, detrás del brillante escaparate de fama y fortuna, se ha desarrollado una historia muy distinta: una de explotación sistemática, contratos depredadores y la priorización constante del beneficio sobre la autenticidad artística. Nuestra banda se opone firmemente a este modelo arraigado, y para entender por qué, primero debemos mirar hacia atrás y reconocer las cadenas históricas que han atado a los músicos por generaciones (más allá del hecho evidente de que ninguna discográfica – ni grande, ni pequeña, ni diminuta – nos ha ofrecido jamás un contrato justo).",
            "El nacimiento de la música grabada trajo la promesa de un mayor alcance, pero también las primeras señales de peligro para los artistas. En el bullicioso crisol creativo de Tin Pan Alley, a principios del siglo XX, los compositores solían recibir un pago fijo, renunciando a todos los derechos futuros y regalías. Imagina volcar tu alma en una canción, solo para que pertenezca a otros, para siempre. Esto marcó un precedente peligroso: el valor del arte se separó del trabajo y la propiedad intelectual del artista.",
            "Con la aparición de los sellos discográficos, el desequilibrio de poder se consolidó. Los primeros contratos discográficos eran famosos por sus cláusulas laberínticas, a menudo ininteligibles incluso para los propios artistas. Los anticipos, presentados como salvavidas para músicos necesitados, en realidad eran deudas reembolsables. Es decir, cada centavo gastado por el sello en grabaciones, marketing y giras tenía que ser devuelto por el artista con su escasa parte de las regalías futuras. Muchos artistas vivían endeudados eternamente, incluso cuando vendían millones. El sueño de una vida cómoda, a menudo, seguía siendo solo eso: un sueño.",
            "La era del rock and roll a mediados del siglo XX no trajo alivio. Los artistas cedían sus derechos editoriales – el activo más valioso de la industria – por migajas. Los ingresos editoriales generados por películas, anuncios o versiones, enriquecían a los sellos y editores, mientras los creadores apenas veían una fracción. Las bandas firmaban contratos por varios álbumes, obligadas a producir música a ritmos dictados por intereses corporativos, no por la inspiración. El control creativo era inexistente: el sello decidía desde las canciones hasta la portada, moldeando artistas como productos.",
            "La llegada de MTV en los años 80 trajo una era de espectáculo visual, pero también más control. Los videoclips eran esenciales para la promoción, pero sus costos altísimos recaían en los propios artistas, aumentando su deuda. El talento crudo se desplazó por la imagen pulida. Las bandas eran empaquetadas y presentadas con una estética homogénea. La industria, hambrienta de éxitos, homogeneizó el sonido, empujando fórmulas comerciales sobre la exploración artística. Los que desafiaban estas normas eran marginados o descartados.",
            "Décadas de historias muestran artistas financieramente arruinados, creativamente sofocados y descartados por una industria que decía apoyarlos. Desde TLC, que se declaró en bancarrota tras vender millones, hasta Little Richard luchando toda su vida por recuperar sus derechos, el patrón se repite. La industria se construyó sobre un modelo extractivo que trata la música como mercancía, sin valorar a sus creadores.",
            "Esta historia de explotación no es solo un aviso: es el fundamento de nuestra ética. Nos negamos a participar en un sistema que ha devaluado sistemáticamente a los artistas y mercantilizado el arte. Creemos en otro camino, basado en la autenticidad, la independencia y la conexión directa con quienes realmente aprecian la música. Este contexto histórico no es un lamento: es una declaración. Estamos decididos a forjar una nueva vía, libre de los ecos de explotación que han atormentado la música por demasiado tiempo."
        ],
        article_two: [
            "El cambio de milenio prometía una revolución. Internet, en un principio aclamado como el gran democratizador, supuestamente liberaría a los artistas del control de la industria tradicional. La era de la piratería, aunque disruptiva, destacó sin querer el poder del acceso directo. Luego llegaron las redes sociales, ofreciendo a los artistas una línea directa con sus fans. Pero lo que empezó como una promesa de libertad se ha convertido, para muchos, en una nueva y sutil forma de control: las cadenas algorítmicas de la era del streaming. Nuestra banda entiende estos dilemas digitales de forma íntima, y por eso mismo hemos elegido un camino radicalmente distinto, priorizando la música por encima de todo.",
            "Al principio, el panorama digital parecía una frontera sin límites. Los músicos podían conectar con oyentes en todo el mundo, compartir su obra con una facilidad sin precedentes y eludir a los guardianes tradicionales. Pero con el tiempo surgieron nuevos guardianes, disfrazados de plataformas de streaming y sus algoritmos aparentemente neutrales. Estas plataformas, aunque convenientes para los oyentes, han devaluado sistemáticamente la música y, en consecuencia, a los artistas que la crean. Sus modelos de pago son notoriamente opacos y ridículamente bajos, haciendo casi imposible que la mayoría de los músicos vivan solo de los streams.",
            "Para las bandas nuevas y emergentes, la situación es aún más grave. El algoritmo se ha convertido en el nuevo A&R, decidiendo qué se escucha y por quién. Los artistas son empujados a una cinta interminable de “contenido”, obligados a producir videos cortos, seguir tendencias fugaces y perseguir momentos virales para obtener siquiera una pizca de visibilidad. El enfoque se aleja de crear música atemporal para centrarse en contenido desechable, fragmentando la energía creativa y sacrificando la profundidad artística por un efímero favor algorítmico. Ya no se trata de cultivar arte, sino de alimentar a una bestia digital insaciable.",
            "Peor aún, la era algorítmica ha impulsado la música “procesada”. Piénsalo: canciones estériles diseñadas por comités dentro de las grandes discográficas, fruto de múltiples compositores y productores anónimos que crean un sonido según fórmulas de mercado, destinado a atraer a la mayor audiencia posible. Los programas de talentos son otro reflejo de esta tendencia: reducen la expresión artística a un espectáculo competitivo, donde la vendibilidad supera al talento genuino. La autenticidad se sacrifica en nombre del atractivo masivo, y el alma de la música se pierde en la persecución del éxito fabricado.",
            "Aquí es donde nuestra banda traza una línea clara en la arena digital. Rechazamos las cadenas algorítmicas y la cinta de contenido. Nos negamos a comprometer nuestra integridad artística por tendencias fugaces o algoritmos corporativos. Para nosotros, la música lo es todo. Es el principio, el centro y el final de nuestro proceso creativo. Cada nota, cada letra, cada ritmo es creado con devoción absoluta a nuestra visión artística – no a una fórmula de mercado.",
            "Nuestra solución nace de este compromiso inquebrantable con la pureza artística: somos 100% autosuficientes y ferozmente independientes. No hay sellos, ni jefes corporativos, ni algoritmos dictando nuestro sonido. Nosotros financiamos cada aspecto de nuestra producción creativa.",
            "Cuando escuchas nuestra música, estás experimentando algo verdaderamente auténtico. Estás apoyando a artistas que ponen todo su ser en su arte, sin agendas corporativas ni presiones algorítmicas. Formas parte de un movimiento que cree en el valor intrínseco de la música, no solo en su capacidad para ser consumida pasivamente. No somos un producto: somos pasión. No somos contenido: somos artistas. Estamos rompiendo las cadenas algorítmicas, una nota auténtica a la vez – y te invitamos a unirte a este viaje rebelde."
        ],
    },
    music: {
        title: 'Escucha & Apoya'
    }
}