export default {
    nav: {
        intro: 'Introduction',
        mission: 'Mission',
        music: 'Musique'
    },
    intro: {
        introCopy: [
            "Nous sommes un groupe indépendant engagé à faire de la musique en dehors du circuit traditionnel. Nous ne publions pas nos chansons sur les plateformes de streaming et refusons de participer aux rouages habituels de l’industrie musicale. Pas de labels, pas d’algorithmes, aucun compromis — juste de la musique faite avec le cœur, l’intention et une liberté créative totale.",
            "Chaque chanson que nous partageons est une partie de ce que nous sommes. Nous enregistrons, produisons et distribuons tout nous-mêmes car nous croyons que la musique doit aller directement de l’artiste à l’auditeur — brute, vraie et sans filtre. Nous ne le faisons pas pour les classements ou la gloire. Nous le faisons parce que nous aimons ce que nous faisons et voulons le partager avec ceux qui s’en soucient vraiment.",
            "Quand vous nous soutenez, vous ne faites pas qu’acheter un morceau — vous contribuez à maintenir ce rêve vivant, à financer du nouveau matériel, à écrire de nouvelles chansons et à rester totalement indépendants. Merci de faire partie de quelque chose de réel."
        ]
    },
    mission: {
        title: 'Notre Mission',
        articleOneH1: "Les Échos de l'Exploitation : Un Siècle de Chaînes Musicales",
        missionCopy: [
            "La musique underground est un état d’esprit : une indépendance farouche face aux tendances commerciales et aux attentes de l’industrie. Elle est brute, authentique, née de l’urgence créative, et non des formules marketing.",
            "Les deux dernières décennies ont transformé la musique, de la piraterie qui a bouleversé l’industrie à la promesse des réseaux sociaux de relier directement artistes et fans. Mais cette liberté a un prix. Les algorithmes des plateformes de streaming sont devenus les nouveaux gardiens, dévalorisant la musique et forçant les artistes indépendants dans un cycle sans fin de création de contenu — à courir après les likes et les tendances pour être vus. La musique est devenue du bruit de fond, sa profondeur sacrifiée pour une visibilité éphémère.",
            "C’est pourquoi nous ne publions pas en streaming et ne recherchons pas l’approbation algorithmique. Nous croyons que notre musique mérite mieux qu’une simple consommation passive. Nous refusons un système qui dévalorise les artistes et met en avant les tendances virales plutôt que l’authenticité. Nous voulons un lien direct : pas d’intermédiaires, pas de gardiens — juste nous et vous, l’auditeur.",
            "Ceci est notre rock & roll underground : fort, honnête et entièrement à nous. Nous faisons de la musique parce que nous le ressentons, pas pour suivre des tendances ou plaire aux algorithmes. Nous défendons la musique comme art, rébellion et vérité. Si vous êtes ici, c’est que vous y croyez aussi. Merci de garder la vraie musique vivante.",
            "Si vous voulez aller plus loin dans notre vision, voici deux articles plus détaillés"
        ],
        article_one: [
            "Depuis plus d’un siècle, l’industrie musicale dominante a tissé une narration séduisante où les rêves artistiques deviennent réalité. Pourtant, derrière cette façade scintillante de gloire et de fortune, se cache une autre histoire — celle d’une exploitation systémique, de contrats prédateurs et d’une priorité constante donnée au profit plutôt qu’à l’art véritable. Notre groupe s’oppose fermement à ce modèle enraciné, et pour comprendre pourquoi, il faut d’abord regarder en arrière, vers les chaînes historiques qui ont entravé les musiciens depuis des générations (au-delà du fait évident qu’aucune major – ni aucune maison de disque, grande ou petite – ne nous a jamais proposé un contrat équitable).",
            "L’avènement de la musique enregistrée a apporté la promesse d’une plus grande portée, mais aussi les premiers signes de problèmes pour les artistes. Dans le creuset créatif de Tin Pan Alley, au début du XXe siècle, les auteurs et compositeurs étaient souvent payés un montant forfaitaire, renonçant à tous les droits futurs et royalties. Imaginez mettre votre âme dans une chanson, pour qu’elle appartienne à quelqu’un d’autre, à jamais. Cela a instauré un précédent dangereux : la valeur de l’art était séparée du travail et de la propriété intellectuelle de l’artiste.",
            "Avec l’émergence des maisons de disques, le déséquilibre de pouvoir s’est renforcé. Les premiers contrats étaient célèbres pour leurs clauses labyrinthiques, souvent incompréhensibles même pour les artistes qui les signaient. Les avances, présentées comme un salut pour les musiciens précaires, étaient en réalité des dettes à rembourser. Cela signifiait que chaque centime dépensé par le label pour l’enregistrement, la promotion et les tournées devait être remboursé par l’artiste à partir de sa maigre part des royalties. Beaucoup restaient éternellement endettés envers leur label, même en vendant des millions. Le rêve d’une vie confortable restait un rêve.",
            "L’essor du rock and roll au milieu du XXe siècle n’a pas interrompu l’exploitation. Les artistes cédaient leurs droits d’édition – l’actif le plus précieux de la musique – pour presque rien. Les revenus générés par les utilisations de leurs chansons dans les films, publicités ou reprises enrichissaient les éditeurs et labels, tandis que les créateurs ne touchaient qu’une infime fraction. Les groupes étaient liés par des contrats pluri-albums, obligés de produire à un rythme dicté par des impératifs commerciaux, non créatifs. Le contrôle artistique n’existait pas : le label décidait de tout, des chansons à la pochette, transformant les artistes en produits.",
            "Avec l’arrivée de MTV dans les années 1980, une nouvelle ère de spectacle visuel est née – mais aussi un nouveau niveau de contrôle. Les clips devenaient indispensables, mais leurs coûts astronomiques étaient souvent à la charge des artistes. L’image lisse prenait le dessus sur le talent brut. Les groupes étaient emballés, marketés, leur individualité effacée au profit d’une esthétique standardisée. L’obsession du tube créa une uniformisation du son, les maisons poussant vers des recettes commerciales plutôt que des explorations artistiques. Ceux qui résistaient étaient souvent mis à l’écart.",
            "Des histoires d’artistes ruinés, bridés ou jetés comme des déchets ont surgi sans fin. De TLC déclarant faillite malgré des millions d’albums vendus, à Little Richard luttant toute sa vie pour ses droits d’auteur, le scénario se répète. L’industrie musicale s’est bâtie sur un modèle extractif, marchandisant la création en oubliant les humains derrière les chansons.",
            "Cette histoire d’exploitation n’est pas juste un avertissement : elle est au cœur de l’éthique de notre groupe. Nous refusons de participer à un système qui dévalorise l’artiste et transforme l’art en marchandise. Nous croyons en un autre chemin : l’authenticité, l’indépendance, et une connexion directe entre créateurs et public. Ce contexte historique n’est pas une plainte : c’est une déclaration de principe. Nous forgeons une nouvelle voie, affranchie des chaînes d’un système obsolète."
        ],
        article_two: [
            "Le tournant du millénaire promettait une révolution. Internet, salué à ses débuts comme l’ultime outil de démocratisation, était censé libérer les artistes de l’emprise de l’industrie traditionnelle. L’ère du piratage, bien que perturbatrice, a mis en évidence le pouvoir de l’accès direct. Puis sont arrivés les réseaux sociaux, offrant aux artistes un lien direct avec leurs fans. Mais ce qui avait commencé comme une promesse de liberté s’est transformé, pour beaucoup, en une nouvelle forme insidieuse de contrôle : les chaînes algorithmiques de l’ère du streaming. Notre groupe connaît intimement ces dilemmes numériques, et c’est précisément pour cela que nous avons choisi une voie radicalement différente, en plaçant la musique avant tout.",
            "Au début, le paysage numérique ressemblait à un territoire sans limites. Les musiciens pouvaient atteindre des auditeurs dans le monde entier, partager leur travail avec une facilité inédite et contourner les gardiens traditionnels. Mais avec le temps, de nouveaux gardiens sont apparus, déguisés en plateformes de streaming et en algorithmes soi-disant neutres. Ces plateformes, bien qu’utiles pour les auditeurs, ont systématiquement dévalorisé la musique – et par extension, les artistes. Les modèles de rémunération sont notoirement opaques et dérisoires, rendant presque impossible pour la plupart des artistes de vivre de leurs écoutes.",
            "Pour les nouveaux groupes, la situation est encore pire. L’algorithme est devenu le nouvel A&R, décidant de ce qui est entendu et par qui. Les artistes sont poussés dans une course effrénée au « contenu », obligés de produire sans cesse des vidéos courtes, de participer à des tendances éphémères et de courir après des instants viraux pour obtenir un peu de visibilité. L’attention se détourne de la création de musique intemporelle au profit de contenus jetables, fragmentant l’énergie créative et sacrifiant la profondeur artistique à l’autel de l’algorithme. Ce n’est plus nourrir l’art, c’est nourrir une bête numérique insatiable.",
            "Pire encore, l’âge des algorithmes a vu naître la musique « traitée ». Pensez à ces morceaux aseptisés produits par des comités dans les grandes maisons de disques – créés par des auteurs et producteurs anonymes pour coller aux formules du marché et plaire au plus grand nombre. Les émissions de talents en sont l’illustration : elles réduisent l’expression artistique authentique à un spectacle compétitif, où la vendabilité prime sur le talent brut et la vision singulière. L’authenticité est sacrifiée sur l’autel de l’attrait de masse, et l’âme de la musique s’efface au profit du hit formaté.",
            "C’est là que notre groupe trace une ligne claire dans le sable numérique. Nous refusons les chaînes algorithmiques et la course au contenu. Nous refusons de compromettre notre intégrité artistique pour des tendances éphémères ou les caprices d’un algorithme corporatif. Pour nous, la musique est tout. Elle est le début, le milieu et la fin de notre processus créatif. Chaque note, chaque parole, chaque rythme est conçu avec une fidélité totale à notre vision artistique – pas à une formule de marché.",
            "Notre solution découle de cet engagement inébranlable envers la pureté artistique : nous sommes 100 % autonomes et farouchement indépendants. Pas de label, pas de patron, pas d’algorithme pour nous dicter notre son. Nous finançons nous-mêmes chaque aspect de notre création.",
            "Quand vous écoutez notre musique, vous vivez quelque chose d’authentique. Vous soutenez des artistes qui mettent leur âme dans leur art, libérés des agendas corporatifs ou des pressions algorithmiques. Vous faites partie d’un mouvement qui croit en la valeur intrinsèque de la musique, pas seulement en sa capacité à divertir passivement. Nous ne sommes pas un produit : nous sommes une passion. Nous ne sommes pas du contenu : nous sommes des artistes. Nous brisons les chaînes algorithmiques, une note authentique à la fois – et nous vous invitons à nous rejoindre dans ce voyage rebelle."
        ],
    },
    music: {
        title: 'Écouter & Soutenir'
    }
}