export default {
    nav: {
        intro: 'Introduzione',
        mission: 'Missione',
        music: 'Musica'
    },
    intro: {
        introCopy: [
            "Siamo una band indipendente impegnata a fare musica fuori dai circuiti mainstream. Non pubblichiamo le nostre canzoni sulle piattaforme di streaming e rifiutiamo di prendere parte ai meccanismi tradizionali dell’industria musicale. Niente etichette, niente algoritmi, nessun compromesso — solo musica fatta con cuore, intenzione e totale libertà creativa.",
            "Ogni canzone che condividiamo è un pezzo di ciò che siamo. Registriamo, produciamo e distribuiamo tutto da soli perché crediamo che la musica debba arrivare direttamente dall’artista all’ascoltatore — cruda, reale e non filtrata. Non lo facciamo per le classifiche o la fama. Lo facciamo perché amiamo ciò che facciamo e vogliamo condividerlo con chi lo apprezza davvero.",
            "Quando ci supporti, non stai solo acquistando una traccia — stai tenendo vivo questo sogno, ci aiuti a comprare nuova attrezzatura, scrivere nuove canzoni e restare completamente indipendenti. Grazie per far parte di qualcosa di vero."
        ]
    },
    mission: {
        title: 'La Nostra Missione',
        articleOneH1: 'Gli Echi dello Sfruttamento: Un Secolo di Catene Musicali',
        missionCopy: [
            "La musica underground è un’attitudine: un’indipendenza feroce dalle tendenze commerciali e dalle aspettative dell’industria. È grezza, autentica, e nasce dall’urgenza creativa, non da formule di mercato.",
            "Gli ultimi due decenni hanno trasformato la musica: dalla pirateria che ha sconvolto tutto alla promessa dei social media di connettere direttamente artisti e fan. Ma questa libertà aveva un prezzo. Gli algoritmi delle piattaforme di streaming sono diventati i nuovi guardiani, svalutando la musica e costringendo gli artisti indipendenti a un ciclo senza fine di creazione di contenuti — inseguendo like e tendenze solo per essere visti. La musica è diventata rumore di fondo, la sua profondità sacrificata per una visibilità fugace.",
            "Ecco perché non pubblichiamo in streaming e non inseguiamo l’approvazione degli algoritmi. Crediamo che la nostra musica meriti più di un ascolto distratto. Rifiutiamo un sistema che svaluta gli artisti e privilegia le tendenze virali rispetto all’arte autentica. Vogliamo un legame diretto: nessun intermediario, nessun guardiano — solo noi e te, l’ascoltatore.",
            "Questo è il nostro rock & roll underground: forte, sincero e interamente nostro. Facciamo musica perché lo sentiamo, non per seguire mode o accontentare gli algoritmi. Crediamo nella musica come arte, ribellione e verità. Se sei qui, anche tu ci credi. Grazie per mantenere viva la musica vera.",
            "Se vuoi approfondire le nostre ragioni, ecco due articoli più lunghi"
        ],
        article_one: [
            "Per oltre un secolo, l’industria musicale tradizionale ha alimentato una narrativa affascinante fatta di sogni artistici che si realizzano. Eppure, dietro la scintillante facciata di fama e ricchezza, si è sviluppata una storia ben diversa: una storia di sfruttamento sistemico, contratti predatori e costante priorità al profitto rispetto all’arte autentica. La nostra band si oppone fermamente a questo modello radicato e, per capire perché, bisogna prima guardare alle catene storiche che hanno legato i musicisti per generazioni (oltre all’ovvia constatazione che nessuna major – né alcuna etichetta minore o microscopica – ci ha mai offerto un contratto equo).",
            "L’alba della musica registrata portò con sé la promessa di una maggiore diffusione, ma anche i primi segnali di problemi per gli artisti. Nella vivace fucina creativa di Tin Pan Alley all’inizio del XX secolo, compositori e autori venivano spesso pagati con una tariffa fissa, cedendo tutti i diritti futuri e le royalty. Immagina di riversare la tua anima in una canzone, solo per vederla posseduta e sfruttata da altri, per sempre. Si creò così un pericoloso precedente: il valore dell’arte veniva separato dal lavoro e dalla proprietà intellettuale dell’artista.",
            "Con l’emergere delle etichette discografiche, lo squilibrio di potere si consolidò. I primi contratti discografici erano famigerati per le clausole complesse, spesso incomprensibili persino agli artisti che li firmavano. Gli anticipi, presentati come una salvezza per i musicisti in difficoltà, erano in realtà debiti da rimborsare. Questo significava che ogni centesimo speso dall’etichetta per registrazioni, marketing e tour doveva essere restituito dall’artista con la sua esigua parte delle royalty future. Molti artisti si ritrovavano eternamente in debito con le loro etichette, anche se vendevano milioni di dischi. Il sogno di vivere comodamente restava solo un sogno.",
            "Negli anni ’50 e ’60, con l’ascesa del rock and roll, lo sfruttamento proseguì indisturbato. Gli artisti cedevano i diritti editoriali – l’asset più prezioso del settore – per pochi spiccioli. I ricavi editoriali, provenienti dall’uso dei brani in film, pubblicità o cover, diventavano miniere d’oro per etichette ed editori, mentre i creatori vedevano solo una minima parte del vero valore. Le band erano spesso vincolate a contratti per più album, indipendentemente dal successo, costrette a produrre musica a ritmi serrati imposti da logiche aziendali e non da ispirazione creativa. Il controllo artistico era inesistente: l’etichetta decideva su tutto, dalla selezione dei brani alla copertina, trasformando gli artisti in prodotti da vendere invece di valorizzarne la visione personale.",
            "L’arrivo di MTV negli anni ’80 segnò una nuova era fatta di spettacolo visivo e di ulteriore controllo. I videoclip, ormai essenziali per la promozione, avevano costi esorbitanti spesso a carico degli artisti stessi, aggravando i debiti verso le etichette. L’attenzione si spostò dal talento musicale all’immagine patinata e alla carisma costruita. Le band venivano confezionate e proposte al pubblico con un’estetica conforme alle mode del momento, sacrificando l’individualità. La ricerca del successo commerciale portò a un suono sempre più omologato, con i discografici che spingevano verso formule vincenti a discapito della sperimentazione artistica. Chi osava deviare da queste logiche rischiava di essere ignorato o lasciato a casa.",
            "Negli anni, sono emerse innumerevoli storie di artisti finanziariamente rovinati, creativamente soffocati e infine abbandonati dall’industria che diceva di sostenerli. Dai TLC che dichiararono bancarotta pur avendo venduto milioni di dischi, alla lotta di una vita di Little Richard per riottenere i diritti sulle proprie canzoni: il copione si ripete. L’industria musicale è stata costruita su un modello estrattivo, dove la creatività viene trattata come merce da acquistare a poco prezzo e rivendere al massimo, senza alcun rispetto per chi la crea.",
            "Questa storia di sfruttamento non è solo un monito: è il motivo per cui la nostra band esiste con un’etica precisa. Rifiutiamo di far parte di un sistema che ha costantemente svalutato gli artisti e mercificato l’arte. Crediamo in una strada diversa, fondata sull’autenticità, sull’indipendenza e su un rapporto diretto tra chi crea e chi ama davvero la musica. Questo contesto storico non è solo un lamento: è una dichiarazione d’intenti. Vogliamo tracciare una nuova via, libera dagli echi di un’industria che ha oppresso la musica per troppo tempo."
        ],
        article_two: [
            "L’inizio del nuovo millennio prometteva una rivoluzione. Internet, inizialmente accolto come il grande livellatore sociale, avrebbe dovuto liberare gli artisti dalla morsa dell’industria musicale tradizionale. L’era della pirateria, pur essendo destabilizzante, ha messo involontariamente in luce il potere dell’accesso diretto. Poi sono arrivati i social media, offrendo agli artisti un contatto diretto con i fan. Ma ciò che era iniziato come una promessa di libertà si è trasformato, per molti, in una nuova e subdola forma di controllo: le catene algoritmiche dell’era dello streaming. La nostra band conosce bene questi dilemmi digitali, ed è proprio per questo che abbiamo scelto un percorso radicalmente diverso, mettendo la musica al primo posto.",
            "All’inizio, il paesaggio digitale sembrava una frontiera sconfinata. I musicisti potevano connettersi con ascoltatori in tutto il mondo, condividere il proprio lavoro con facilità senza precedenti, e bypassare i tradizionali guardiani dell’industria. Ma col passare del tempo, sono emersi nuovi custodi, mascherati da piattaforme di streaming e dai loro algoritmi apparentemente neutrali. Queste piattaforme, pur offrendo comodità agli ascoltatori, hanno sistematicamente svalutato la musica e, di conseguenza, gli artisti che la creano. I modelli di pagamento sono notoriamente opachi e irrisori, rendendo praticamente impossibile per la maggior parte degli artisti guadagnarsi da vivere solo con gli stream.",
            "Per le band nuove ed emergenti, la situazione è ancora più grave. L’algoritmo è diventato il nuovo A&R, decidendo cosa viene ascoltato e da chi. Gli artisti sono spinti in un ciclo incessante di “contenuti”, costretti a produrre continuamente video brevi, partecipare a trend effimeri e inseguire momenti virali per ottenere anche solo un briciolo di visibilità. L’attenzione si sposta dalla creazione di musica senza tempo alla produzione di contenuti usa e getta, frammentando l’energia creativa e sacrificando la profondità artistica in nome del favore algoritmico. Non si tratta più di promuovere l’arte, ma di nutrire una bestia digitale insaziabile.",
            "Ancora peggio, l’era degli algoritmi ha favorito l’ascesa della musica “processata”. Pensate alle tracce sterili e progettate a tavolino dalle major: il frutto di team anonimi di autori e produttori che costruiscono a tavolino un suono fatto per soddisfare formule di mercato e attrarre il pubblico più ampio possibile. I talent show incarnano questa tendenza, riducendo l’espressione artistica autentica a un concorso di popolarità, dove la vendibilità supera il talento e la visione personale. L’autenticità viene sacrificata sull’altare dell’appeal di massa, e l’anima della musica si perde nella caccia al successo prefabbricato.",
            "È qui che la nostra band traccia una linea netta nella sabbia digitale. Rifiutiamo le catene algoritmiche e la corsa al contenuto. Rifiutiamo di compromettere la nostra integrità artistica per inseguire mode passeggere o algoritmi aziendali. Per noi, la musica è tutto. È l’inizio, il centro e la fine del nostro processo creativo. Ogni nota, ogni parola, ogni ritmo è frutto di una dedizione incrollabile alla nostra visione artistica – non a una formula di mercato.",
            "La nostra soluzione nasce proprio da questo impegno verso la purezza artistica: siamo al 100% autosufficienti e fieramente indipendenti. Nessuna etichetta, nessun padrone aziendale, nessun algoritmo a dettare il nostro suono. Finanziamo autonomamente ogni fase della nostra produzione creativa.",
            "Quando ascolti la nostra musica, stai vivendo qualcosa di autentico. Stai supportando artisti che mettono tutto sé stessi nel proprio lavoro, liberi da agende aziendali e pressioni algoritmiche. Fai parte di un movimento che crede nel valore intrinseco della musica, non solo nel suo potenziale come intrattenimento passivo. Non siamo un prodotto: siamo una passione. Non siamo contenuti: siamo artisti. Stiamo spezzando le catene algoritmiche, una nota autentica alla volta – e ti invitiamo a unirti a noi in questo viaggio ribelle."
        ]
    },
    music: {
        title: 'Ascolta & Supporta'
    }
}
